<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span><ul class="toc-item"><li><span><a href="#Загрузка-исходных-данных" data-toc-modified-id="Загрузка-исходных-данных-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Загрузка исходных данных</a></span><ul class="toc-item"><li><span><a href="#Вывод:" data-toc-modified-id="Вывод:-1.1.1"><span class="toc-item-num">1.1.1&nbsp;&nbsp;</span>Вывод:</a></span></li></ul></li><li><span><a href="#Создание-датасетов-с-признаками-и-целевым-признаком" data-toc-modified-id="Создание-датасетов-с-признаками-и-целевым-признаком-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Создание датасетов с признаками и целевым признаком</a></span><ul class="toc-item"><li><span><a href="#Вывод:" data-toc-modified-id="Вывод:-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>Вывод:</a></span></li></ul></li></ul></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span><ul class="toc-item"><li><span><a href="#Определение-исходных-данных" data-toc-modified-id="Определение-исходных-данных-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Определение исходных данных</a></span></li><li><span><a href="#Математиеская-проверка-влияния-умножения-матрицы-признаков-на-обратимую-матрицу" data-toc-modified-id="Математиеская-проверка-влияния-умножения-матрицы-признаков-на-обратимую-матрицу-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Математиеская проверка влияния умножения матрицы признаков на обратимую матрицу</a></span></li><li><span><a href="#Вывод-:" data-toc-modified-id="Вывод-:-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Вывод :</a></span></li></ul></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Вывод:" data-toc-modified-id="Вывод:-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Вывод:</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

## Загрузка данных

### Загрузка исходных данных

Для удобства работы в первой ячейке имеет смысл загрузить все используемые нами при работе бибилиотеки:


In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import warnings
warnings.filterwarnings('ignore')

Загрузим основной датасет и сохраним его в переменной data: 


In [2]:
data = pd.read_csv('/datasets/insurance.csv')

Посмотрим на загруженные данные, оценим наличие и количество пропусков, соответствие типов данных столбцов данным которые в них размещены: 

In [3]:
data.info()
data.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
Пол                  5000 non-null int64
Возраст              5000 non-null float64
Зарплата             5000 non-null float64
Члены семьи          5000 non-null int64
Страховые выплаты    5000 non-null int64
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0
5    1     43.0   41000.0            2                  1
6    1     39.0   39700.0            2                  0
7    1     25.0   38600.0            4                  0
8    1     36.0   49700.0            1                  0
9    1     32.0   51700.0            1                  0

Для удобства работы переведем название столбцов в нижний регистр:

In [4]:
data.columns = map(str.lower, data.columns)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
пол                  5000 non-null int64
возраст              5000 non-null float64
зарплата             5000 non-null float64
члены семьи          5000 non-null int64
страховые выплаты    5000 non-null int64
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


#### Вывод:
Как видно из загруженных данных, пропуски в датасете отсутствуют, все столбцы имеют необходимый формат данных, ошибок нет. Данные пригодны к дальнейшей обработке и работе с ними. 

### Создание датасетов с признаками и целевым признаком

In [5]:
features = data.drop('страховые выплаты', axis = 1)
target = data['страховые выплаты']
features.head()


пол  возраст  зарплата  члены семьи
0    1     41.0   49600.0            1
1    0     46.0   38000.0            1
2    0     29.0   21000.0            0
3    0     21.0   41700.0            2
4    1     28.0   26100.0            0

In [6]:
target.head()

0    0
1    1
2    0
3    0
4    0
Name: страховые выплаты, dtype: int64

#### Вывод: 
Мы создали два датасета с признаками и целевым признаком. Теперь данные готовы для использования их в задачах машинного обучения.  

## Умножение матриц

### Определение исходных данных

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

### Математиеская проверка влияния умножения матрицы признаков на обратимую матрицу

Как понятно из условия задачи - нам необходимо умножить матрицу признаков на обратимую матрицу P, которая является квалратной размерности 4x4, так как у нас таблица имеет размерность 5000x4. А для умножения матриц необходимо, чтобы смежные размерности совпадали, ведь если разные смежные размерности - умножение матриц невозможно. 

Итак, примем новое условие: 

$$
X = XP
$$

Для начала подставим формулу обучения $w$  в основную формулу предсказания $a$  для наглядности:

$$
a = Xw = X(X^T X)^{-1} X^T y
$$

Теперь подставим наше значение матрицы $X$ в данную формулу, пометим $a'$, для наглядности: 

$$
a' = XPw = XP((XP)^T XP)^{-1} (XP)^T y
$$

Раскроем скобки с траспонированием матриц, ведь $(AB)^T = B^T A^T$, исходя из этого получим: 

$$
a' = XP(P^T X^T XP)^{-1} P^T X^T y
$$

Так как для матричных операций справедливо выражение $(AB)С = A(BC)$, вынесем за скобки $P^T$ и $P$, получим:

$$
a' = XP(P^T(X^T XP) P)^{-1} P^T X^T y
$$

Так как,  матрица признаков $X$ является прямоугольной, то получить ее обратную матрицу невозможно, так как она является необратимой, но произведение матрицы $XX^T$ вполне может дать квадратную матрицу, значит мы не сможем раскрыть данные скобки при обращении. Теперь применим к нашей формуле правило $(AB)^{-1} = B^{-1} A^{-1}$:

$$
a' = X P P^{-1} (X^T XP)^{-1} (P^T)^{-1} P^T X^T y
$$

У нас получилось две единичные матрицы, так как $A A^{-1} = E$, а $AE = A$, таким образом можно сократить выражения $P P^{-1}$ и $(P^T)^{-1} P^T$: 

$$
a' = X (X^T XP)^{-1}X^T y = Xw
$$

Как видно выше мы получили стандартную формулу предсказания, которая совпадает с исходной формулой, соответственно верно утверждение:

$$
a = a'
$$


**Ответ:** Качество линейной регрессии не изменится.

**Обоснование:** Утверждение приведенное выше справедливо, так как умножение матрицы признаков на обратимую матрицу в конечном итоге дает изначальную формулу расчета предсказания. И соответственно умножение никак не влияет на качество модели линейной регресси, так как она остается в изначальном состоянии. 

### Вывод :

Путем математических преобразований мы выяснили, что умножение матрицы признаков на обратимую матрицу не влияет на качество модели линейной регрессии. Соответственно в следующем пункте, нам можно с увернностью использовать данное свойство формулы расчета предсказаний. 


## Алгоритм преобразования

**Алгоритм**
Так как мы выяснили, что умножение матрицы на обратимую матрицу не влияет на качество линейной регрессии, то для кодирования данных мы умножим матрицу признаков на рандомную обратимую матрицу(квадртатную) размерностью 4x4   

**Обоснование**

Исходя из полученной нами формулы в пункте 2, умножение обратимой матрицы на матрицу признаков не оказывает влияние на качество линейной регрессии, поэтому есть смысл зашифровать данные с помощью умножения на матрицу. 

** При таком подходе, обратная к нашей рандомной обратимой матрице, матрица будет являться ключом к расшифровке данных:**

$$
AA^{-1} = E
$$

Соответственно умножение на обратимую и обратную матрицу даст в итоге умножение на еденичную мтарицу, а это в свою очередь даст нам искомую матрицу: 

$$
BAA^{-1} = BE = B
$$

## Проверка алгоритма

Для проверки алгоритма нам необходимо(как указано выше) создать случайную обратимую матрицу размерности 4* 4, умножить ее на матрицу признаков, после чего обучить на ней модель линейной регрессии из sklearn, найти метрику качества R2, затем сравнить результат с метрикой модели обученной на исходной матрице признаков.

Итак, приступим. Для начала преобразуем в матрицу датафрейм признаков: 

In [7]:
features_matrix = features.values
print(features_matrix)

[[1.00e+00 4.10e+01 4.96e+04 1.00e+00]
 [0.00e+00 4.60e+01 3.80e+04 1.00e+00]
 [0.00e+00 2.90e+01 2.10e+04 0.00e+00]
 ...
 [0.00e+00 2.00e+01 3.39e+04 2.00e+00]
 [1.00e+00 2.20e+01 3.27e+04 3.00e+00]
 [1.00e+00 2.80e+01 4.06e+04 1.00e+00]]


Теперь обучим и протестируем модель на исходных данных: 

In [8]:
model = LinearRegression()
model.fit(features_matrix, target)
predictions = model.predict(features_matrix)
print('Метрика R2 для модели линейной регрессии:', r2_score(target, predictions))

Метрика R2 для модели линейной регрессии: 0.42494550286668


Как видно мы получили отрицательную метрику R2, равную 0,42, что не плохо, но у нас и не стоит задачи получить идеальную модель, а проверить работу алгоритма и чтобы значение метрики не ухудшилось, после зашифровки исходных данных. Первым делом создадим матрицу: 

In [9]:
matrix_key = np.array([
    [1,4,2,1],
    [1,3,5,7],
    [2,5,4,6],
    [4,5,6,9]
]
)
print(matrix_key)

[[1 4 2 1]
 [1 3 5 7]
 [2 5 4 6]
 [4 5 6 9]]


Умножим матрицу признаков на нашу обратимую, квадратную матрицу: 

In [10]:
features_matrix_key = features_matrix @ matrix_key
print(pd.DataFrame(features_matrix_key, columns = features.columns).head())

       пол   возраст  зарплата  члены семьи
0  99246.0  248132.0  198613.0     297897.0
1  76050.0  190143.0  152236.0     228331.0
2  42029.0  105087.0   84145.0     126203.0
3  83429.0  208573.0  166917.0     250365.0
4  52229.0  130588.0  104542.0     156797.0


Как видно из полученного результата - расшифровать данные без ключа становится крайне затруднительно. В расшифровке данных нам должна помочь обратная нашей матрица. Формула ее нахождения выглядит следующим образом: 

$$
A^{-1} = \frac{1}{|A|} A^T
$$
где : 

$|A|$ - определитель матрицы

$A^T$ - транспонирванная исходная матрица 

Найти ее мы можем применив метод библиотеки NumPy:

In [11]:
matrix_key_inv = np.linalg.inv(matrix_key)
print(matrix_key_inv)

[[ 0.08474576 -0.33898305 -0.3559322   0.49152542]
 [ 0.03389831 -0.13559322  0.45762712 -0.20338983]
 [ 0.62711864  0.49152542 -1.03389831  0.23728814]
 [-0.47457627 -0.10169492  0.59322034 -0.15254237]]


Теперь проверим, что данные действительно рашифруются при умножении на обратную матрицу: 

In [12]:
features_matrix_no_key = features_matrix_key @ matrix_key_inv
print(pd.DataFrame(features_matrix_no_key, columns = features.columns).head())
print(features.head())

            пол  возраст  зарплата   члены семьи
0  1.000000e+00     41.0   49600.0  1.000000e+00
1 -6.492418e-12     46.0   38000.0  1.000000e+00
2 -1.666944e-12     29.0   21000.0 -6.419865e-13
3 -4.788780e-12     21.0   41700.0  2.000000e+00
4  1.000000e+00     28.0   26100.0  8.298362e-13
   пол  возраст  зарплата  члены семьи
0    1     41.0   49600.0            1
1    0     46.0   38000.0            1
2    0     29.0   21000.0            0
3    0     21.0   41700.0            2
4    1     28.0   26100.0            0


Как видно из приведенных выше таблиц, зашифровка и расшифровка данных проходит корректно, данные в расшифрованном виде отличаются от исходный на величину математической погрешности.

**Мы допустили небольшое лирическое отступление, которое позволило нам воочию увидеть, как проходит зашифровка и расшифровка данных нашим алгоритмом.**

Теперь же, пришло время проверить, что метрики моделей обуxенных на исходных и зашифрованных данных не отличаются.

Обучим модель на зашифрованных данных и сравним ее метрику R2 с метрикой модели обученной на исходных данных:

In [13]:
model_key = LinearRegression()
model_key.fit(features_matrix_key, target)
predictions_key = model_key.predict(features_matrix_key)
print('Метрика R2 для модели линейной регрессии с исходными данными:', r2_score(target, predictions))
print('Метрика R2 для модели линейной регрессии с зашифрованными данными:', r2_score(target, predictions_key))

Метрика R2 для модели линейной регрессии с исходными данными: 0.42494550286668
Метрика R2 для модели линейной регрессии с зашифрованными данными: 0.4249455028666702


## Вывод: 

В данном проекте, мы математически, с помощью матричных операций,  доказали, что умножение на обратимую матрицу матрицы признаков не вносит изменений в качество модели линейной регрессии, на практике проверили работу алгоритма, также обучили модели на исходных данных и зашифрованных.

В итоге метрика R2 осталась неизменной. Также мы убедились в том, как с помощью обратной матрицы можно расшифровать зашифрованные данные. 

Соответственно все поставленные в проекте задачи мы решили. 

